### ISSUE TITLE
What is the multiplexer component number?

### ISSUE THREAD

**Issue by askdesigners** [NathaelBoni/KerbalKontroller#8]
Hello! Love this simple controller project. I've been building it with my son but am a bit stumped by what the IC is in the schematic. I assume it's a multiplexer to drive the LEDs but not sure which. Any clarification would be super helpful. Thanks! Great work on this. 

Oh, additionally it would be cool to have either a rendering of the full controller or a photo of what the final assembly looks like. I'm tempted to print the 3d parts but without knowing what it should look like I'm not sure how it should go together.

**Comment by NathaelBoni** [comment]
Yes, I should've listed the parts somewhere, at least the model in the schematics. I have plans to update this repo, in the meanwhile, this is the datasheet for [CD74HC4067](https://www.ti.com/lit/ds/symlink/cd74hc4067.pdf).

About the 3D parts, I really don`t recommend them. I keep them here mostly for storage/backup. The entire structure is too finicky to put in place, I ended up using lots of glue and my solder iron to fuse the plastic together. It looked very nice but it's really hard. If you still wanna do it, I've uploaded two images here.
![fusion3d](https://github.com/NathaelBoni/kerbal-kontroller/assets/8930422/cfe24e03-c26a-446b-a25c-1a8764386301)
![real](https://github.com/NathaelBoni/kerbal-kontroller/assets/8930422/42373743-13dc-44cb-bc1f-2851563df599)

Also, something I should've done is use a 4-axis Joystick instead of those handles. There is one joystick at the base and another one on top, so you can maneuver in all directions with your hands and thumb, but it was very difficult to put it together, I really don't know how that is still working. One like this one from the image below should be much better.
![Screenshot 2023-11-29 005449](https://github.com/NathaelBoni/kerbal-kontroller/assets/8930422/4510121e-3a89-459f-931c-7d4476d8623a)

Good luck, thank you for your interest!
